services:
  web:
    container_name: web
    build:
      context: frontend
      no_cache: true
    image: code-challenge-todo-web
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    healthcheck:
      test: wget -qO- 0.0.0.0:3010 || exit 1
      interval: 1m
    networks:
      - main_network
    ports:
      - 3010:3010
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: backend
      no_cache: true
    image: code-challenge-todo-api
    environment:
      - PORT=3000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    healthcheck:
      test: wget -qO- 0.0.0.0:3000/health || exit 1
      interval: 1m
    networks:
      - main_network
    ports:
      - 3000:3000

networks:
  main_network:
    name: main_network
    driver: bridge
